
[[main]]
  name = "Blogi"
  url = "/blogi/"
  weight = 10

[[main]]
  name = "Tiedotteet"
  url = "/tiedotteet/"
  weight = 15


[[main]]
  name = "Meistä"
  url = "/meista/"
  weight = 20

[[main]]
  name = "Hallinto"
  url = "/hallinto/"
  weight = 25

[[main]]
  name = "Jäseneksi!"
  url = "/jaseneksi-lomake/"
  weight = 30

[[main]]
  name = "UKK"
  url = "/ukk/"
  weight = 35


[[main]]
  name = "Liiton säännöt"
  url = "/saannot/"
  weight = 40

[[main]]
  name = "Tietosuoja"
  url = "/tietosuoja/"
  weight = 45

[[main]]
  name = "Evästeet"
  url = "/evasteet/"
  weight = 50
  
[[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/contact/"
  weight = 60

[[main]]
  name = "<img src=\"/icons/search.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/search/"
  weight = 70

[[main]]
  name = "<img src=\"/icons/facebook.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "https://www.facebook.com/Vapaa-ammattiliitto-VALO-ry-109809381573128/"
  weight = 80
  
  